spring:
  datasource:
    url: jdbc:h2:mem:dtech2025
    username: dtech2025
    password: # Adicione sua senha aqui, se necessário
  jpa: 
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # valid / update / create / create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false	
server:
  port: 8081					