spring:
  datasource:
    url: ${DATABASE_URL}  # Aqui você vai usar a variável de ambiente DATABASE_URL
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}  # Caso queira usar variáveis de ambiente para o username
    password: ${DB_PASSWORD}  # Caso queira usar variáveis de ambiente para a senha
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8082

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
